---
# Test 1: Normal operation - doubling a number
test_name: Make sure server doubles number properly

stages:
  - name: Make sure number is returned correctly
    request:
      url: http://localhost:5000/double
      json:
        number: 5
      method: POST
      headers:
        content-type: application/json
    response:
      status_code: 200
      body:
        double: 10

---
# Test 2: Error handling with invalid inputs
test_name: Check invalid inputs are handled

stages:
  # Stage 1: Invalid number format (string that's not a number)
  - name: Make sure invalid numbers don't cause an error
    request:
      url: http://localhost:5000/double
      json:
        number: dkfsd
      method: POST
    response:
      status_code: 400
      body:
        error: a number was not passed

  # Stage 2: Missing number field
  - name: Make sure it raises an error if a number isn't passed
    request:
      url: http://localhost:5000/double
      json:
        wrong_key: 5
      method: POST
    response:
      status_code: 400
      body:
        error: no number passed
