---
test_name: Get user from JSONPlaceholder API

stages:
  - name: Get user by ID
    request:
      url: https://jsonplaceholder.typicode.com/users/1
      method: GET
    response:
      status_code: 200
      body:
        id: 1
        name: Leanne Graham
        username: Bret
        email: Sincere@april.biz

---
test_name: Get post and verify structure

stages:
  - name: Get first post
    request:
      url: https://jsonplaceholder.typicode.com/posts/1
      method: GET
    response:
      status_code: 200
      body:
        userId: 1
        id: 1
      save:
        body:
          user_id: userId
          
  - name: Get user by saved ID
    request:
      url: https://jsonplaceholder.typicode.com/users/{user_id}
      method: GET
    response:
      status_code: 200
      body:
        id: 1
