---
# Test 1: JWT token validation
# Aligned with tavern-py commit 2a3725b - using nested variables
test_name: Make sure jwt returned has the expected aud value

includes:
  - !include common.yaml

stages:
  - &login_request
    name: login
    request:
      url: "{service.proto}://{service.host}:{service.port}/login"
      json:
        user: test-user
        password: correct-password
      method: POST
    response:
      status_code: 200
      save:
        body:
          test_login_token: token

---
# Test 2: Complete CRUD workflow
test_name: Make sure server doubles number properly

includes:
  - !include common.yaml

stages:
  - &reset_request
    name: reset database for test
    request:
      url: "{service.proto}://{service.host}:{service.port}/reset"
      method: POST
    response:
      status_code: 204

  - *login_request

  - name: post a number
    request:
      url: "{service.proto}://{service.host}:{service.port}/numbers"
      json:
        name: smallnumber
        number: 123
      method: POST
      headers:
        Authorization: "bearer {test_login_token}"
    response:
      status_code: 201

  - name: Make sure its in the db
    request:
      url: "{service.proto}://{service.host}:{service.port}/numbers"
      params:
        name: smallnumber
      method: GET
      headers:
        Authorization: "bearer {test_login_token}"
    response:
      status_code: 200
      body:
        number: 123

  - name: double it
    request:
      url: "{service.proto}://{service.host}:{service.port}/double"
      json:
        name: smallnumber
      method: POST
      headers:
        Authorization: "bearer {test_login_token}"
    response:
      status_code: 200
      body:
        number: 246

---
# Test 3: Error handling - nonexistent number
test_name: Check trying to get a number that we didnt post before returns a 404

includes:
  - !include common.yaml

stages:
  - *reset_request

  - *login_request

  - name: check it doesn't exist yet
    request:
      url: "{service.proto}://{service.host}:{service.port}/numbers"
      params:
        name: whatnumber
      method: GET
      headers:
        Authorization: "bearer {test_login_token}"
    response:
      status_code: 404

---
# Test 4: Error handling - double nonexistent number
test_name: Test doubling a number that doesn't exist

includes:
  - !include common.yaml

stages:
  - *reset_request

  - *login_request

  - name: Make sure doubling something that doesn't exist raises an error
    request:
      url: "{service.proto}://{service.host}:{service.port}/double"
      json:
        name: doesntexist
      method: POST
      headers:
        Authorization: "bearer {test_login_token}"
    response:
      status_code: 404

---
# Test 5: SSL certificate verification
test_name: Test SSL certificate verification with verify keyword

includes:
  - !include common.yaml

stages:
  # Test with verify explicitly set to true (default behavior)
  - name: Login with verify true
    request:
      url: "{service.proto}://{service.host}:{service.port}/login"
      method: POST
      verify: true
      json:
        user: test-user
        password: correct-password
    response:
      status_code: 200
      save:
        body:
          verify_test_token: token

  # Test with verify set to false (skip SSL verification)
  # Note: verify: false is useful in development/testing with self-signed certs
  # Never use in production!
  - name: Login with verify false
    request:
      url: "{service.proto}://{service.host}:{service.port}/login"
      method: POST
      verify: false
      json:
        user: test-user
        password: correct-password
    response:
      status_code: 200

